version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  app:
    image: httpd:latest
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs/
  db:
    image: mysql
    restart: always
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234.
